Separate HUD from Lib code
m-one-w/M1WEngine pull request #209
Opened 2024-02-08 17:40 UTC by owalk

2024-02-08 18:08 UTC, Sean-Nishi commented on m1wengine/abstract_HUD.py
> +        raise NotImplementedError("This method must be implmented.")
typo in Implemented

2024-02-08 18:10 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +    add_box(self, rect, height, width) -> pygame.sprite.Sprite
typehints

2024-02-08 18:12 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +        self, coordinates: tuple, method
typehint for method

2024-02-08 18:13 UTC, Sean-Nishi commented on m1wengine/score_controller.py
> +BOREDOM_INCREASE_MINOTAUR_DEATH = 5
type hints for consts

2024-02-08 18:14 UTC, Sean-Nishi requested changes
Just the few comments

2024-02-08 20:39 UTC, Sean-Nishi commented on m1wengine/abstract_HUD.py
> +LEVEL_HINT_COORDINATES: tuple = (500, 400)
Do we want to keep this a tuple or use/treat as a pygame.Vector2?

2024-02-08 20:39 UTC, Sean-Nishi commented on m1wengine/abstract_HUD.py
> +    _level_hint_txt: pygame.sprite.Sprite
Add "e" to text

2024-02-08 20:40 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +    LEVEL_HINT_BOX_WIDTH: int = 400
Turn into tuple or pygame.Vector2?

2024-02-08 20:41 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +    PAUSE_BUTTON_HEIGHT: int = 30
Turn into tuple or pygame.Vector2?

2024-02-08 20:41 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +    LINE_INDENT: int = 20
Turn into tuple or pygame.Vector2?

2024-02-08 20:42 UTC, Sean-Nishi commented on m1wengine/builders/hud_builder.py
> +        SCORE_BOX_WIDTH: int = 150
Can be tuple or pygame.Vector2 type. In addition, consts should not be declared inside a method. Should be a static param or at least declared in init

2024-02-08 20:45 UTC, Sean-Nishi commented on m1wengine/score_controller.py
> +BOREDOM_INCREASE_MINOTAUR_DEATH: int = 5
Can we turn this into an enum like EATEN_POWERS except called SCORE_INCREASE_VALUES and BOREDOM_INCREASE_VALUES or as a dictionary for all the boredom/score values?

2024-02-08 20:45 UTC, Sean-Nishi requested changes
Just a few stylistic choices

2024-02-08 20:48 UTC, owalk commented on m1wengine/score_controller.py
> +BOREDOM_INCREASE_MINOTAUR_DEATH: int = 5
I like having an enum or map here. I think a map makes more sense because they can share the same value.

2024-02-09 15:16 UTC, owalk commented on m1wengine/builders/hud_builder.py
> +    LINE_INDENT: int = 20
These are not x and y of the same object, makes more sense separate to me.

we could have multiple line indents used without a side indent, or multiple side indents used with no line indent. Let's keep the individual context

2024-02-09 18:16 UTC, Sean-Nishi requested changes
docstrings

2024-02-09 18:51 UTC, Sean-Nishi commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            self._current_state = self._states.Patrol
Call set_state_patrol directly? or do the conditionals in that method mess this up?

2024-02-09 18:52 UTC, Sean-Nishi requested changes
2 more comments

2024-02-09 18:57 UTC, owalk commented on m1wengine/abstract_HUD.py
> +LEVEL_HINT_COORDINATES: tuple = (500, 400)
vecotr2 for access by x and y

2024-02-09 19:01 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            self._current_state = self._states.Patrol
there's no proper way out of being thrown right now. You had it right by setting the default state, but I was seeing NPC's stuck in place. I'll test this again after rebasing onto main

2024-02-09 19:01 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            self._current_state = self._states.Patrol
well, would it should be set_state_default() and the radar should change that to patrol within 1 iteration

2024-02-09 19:18 UTC, owalk commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +            self._current_state = self._states.Patrol
Just tested, and this is still a bug. Until the radar can properly switch from a default state to a passive state of patrol, this implementation is ideal. I'll make a backlog issue to update this logic to use the proper methods after that bug has been fixed

2024-02-09 19:31 UTC, Sean-Nishi approved these changes

2024-02-09 19:32 UTC, merged