Add multiple possible displayed texts to button
m-one-w/M1WEngine pull request #216
Opened 2024-02-10 16:43 UTC by fcpoloia

it will convert the input text to list and iterate the list with each time `iterate_text_list()` is called, changing the displayed text to the next in list, it will loop around if reached the end of a list

2024-02-10 16:47 UTC, owalk commented
This is a small thing but as general feedback, the commit title should be a small denotation of the scope of the commit, be on a single line, start with a capitalized letter, and have no punctuation at the end. I'll add this to a linter later, but it makes the commits much cleaner looking at a glance.

The commit bodies should be full sentences with proper punctuation, and further detail not in the commit title.

2024-02-10 17:00 UTC, owalk requested changes
I haven't reviewed the logic or organization of the code yet. The first focus is on the commit scope issues and formatting issues.

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> -    def update_and_iterate(self):
Code in a single PR should not get added and removed in two separate commits, or removed and added back in in two separate commits.  It adds significant time to the review process. If you need assistance with the git commands to clean your git history just let me know and I can walk you through it in discord or write out the steps and commands in this review comment

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> +                if self.Button_Texts_List[self.index] == self.Button_Texts_List[-1]:
indentation is wrong in this logic block. Most IDE's will let you highlight the logic you want to change the indentation on, and press shift tab to move it backwards, or tab to move it forwards.

The logic needs to be pulled back one level worth of indentation.

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> +        #Increase the index to change the displayed text and reset index if it's already on the last element
Change this comment to proper doc strings. 
```Suggestion
'''Increase the index to change the displayed text.

Reset the index if on the last element.
'''
```

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> +
formatting change in a non-formatting commit.

This is again a small thing and can be ignored for this PR. In general, it's nice to pull all formatting changes into a separate commit so they do no distract from code changes within the more technical commits.

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> +        text,
I would squash this entire commit onto the previous commit as it is within the same scope of the initial commit. Doing it this way just adds time to the PR review process.

2024-02-10 17:00 UTC, owalk commented on m1wengine/button.py
> -    def update_and_iterate(self):
this commit can be squashed into the initial commit. alongside the second commit. At the end, there only needs to be 1 commit in this PR, unless you decide to pull out the whitespace change into its own formatting commit.

2024-02-12 13:17 UTC, owalk commented
I've enabled the GitHub actions so that future pushes will have lint checks run against them.

2024-02-14 13:53 UTC, owalk commented on m1wengine/button.py
> -    def update_and_iterate(self):
To squash commits, I recommend doing the following:

Git rebase -i HEAD~5
# When your text editor opens, mark the commits to squash with the letter 's'
# save and close the text editor
# edit the commit title and body to be scoped to the new resulting commit
# overwrite the changes on the remote branch with a force push
git push origin 'branch-name' --force

2024-02-14 14:46 UTC, fcpoloia commented on m1wengine/button.py
> -    def update_and_iterate(self):
I know how to squash commits, this just something weird happened, I must've not save the config correctly, I don't know what else might've went wrong

2024-02-14 21:44 UTC, owalk requested changes
Here's some of the old readme which has not been pulled into the current repository yet.

You might want to start using the linter script to check your code, it's a lot easier

![image](https://github.com/m-one-w/M1WEngine/assets/10580211/405915c4-455b-45cd-9f7c-f24e7959d3f6)

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +            a char that would split the string into separate elements in list, leave empty if you only want 1 element
this line is to long. the linter is set to a max line length of 88 characters, and it will complain when you push the code again.

To test this locally, run 
flake8 --max-line-length=88 .

![image](https://github.com/fcpoloia/M1WEngine/assets/10580211/edc029b8-cecd-45c7-afe2-2a5eda7c796b)

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +        #Splits text into a list
space after the hashtag on comments

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +        #Dimensions
space after hashtag on comments

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +        #Clicking functionaliti
missing space

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +        'Increase the index to change the displayed text and reset index if its already on the last element'
to keep the docstrings consistent they should open and close with 3 of quotation mark characters

The line length is probably also too long, check with the linter.

```Suggestion
        """Increase the index to change the displayed text and reset index if its already on the last element'"""
```

2024-02-14 21:44 UTC, owalk commented on m1wengine/button.py
> +
the linter is set to disallow new lines at the end of the file

2024-02-16 14:27 UTC, owalk commented on m1wengine/button.py
> +
this one was actually about white spaces, not the new line.

2024-02-17 16:00 UTC, owalk requested changes
Try to get all the changes on a single commit again since it is all in the scope of that first initial commit, and try to get the lint check to pass. You can press "details" to view what is failing. You can also run the "./linter.sh" script to run the checks locally. I have it set up to run that linter check every time I hit save, and find that very helpful.

![image](https://github.com/m-one-w/M1WEngine/assets/10580211/8a61607f-d6b5-4448-bd5d-439f67963b4b)

2024-02-17 16:02 UTC, owalk commented on m1wengine/button.py
> +
![image](https://github.com/m-one-w/M1WEngine/assets/10580211/e8dec7d6-b5cc-4184-a11d-c571e79e46ff)

2024-02-17 16:05 UTC, owalk commented on m1wengine/button.py
> +        """Increase the index to change the displayed text and reset index if its already on the last element"""
![image](https://github.com/m-one-w/M1WEngine/assets/10580211/b51ea3bc-abef-4bd6-8d94-5caac3f0886e)

```Suggestion
        """Iterate through the display button text.
        
        Increase the index to change the displayed text and
        reset index if it's already on the last element
        """
```

2024-02-17 16:48 UTC, owalk requested changes

2024-02-17 16:48 UTC, owalk commented on m1wengine/button.py
> +        self.__text: Text = Text(x, y, self.button_text)
It would be nice to not have any merge commits. This can be squashed into a single commit for the PR

2024-02-17 17:05 UTC, owalk commented on m1wengine/button.py
> +
run the black formatter and this will be fixed automatically. you may need to install it through the requirments.txt if you haven't yet

2024-02-19 15:37 UTC, fcpoloia commented on m1wengine/button.py
> +        self.__text: Text = Text(x, y, self.button_text)
I tried squashing it but it always ends up with either merge error or creates this commit anyway

2024-02-19 15:56 UTC, owalk commented on m1wengine/button.py
> +        self.__text: Text = Text(x, y, self.button_text)
I need a bit more information to help with this. What are the exact steps to squash that come back with a merge error?

2024-02-26 17:50 UTC, Sean-Nishi commented on m1wengine/button.py
> +            a char that would split the string into separate elements
Docstrings should start with a capitalized letter

2024-02-26 17:51 UTC, Sean-Nishi commented on m1wengine/button.py
> +        self.button_text = ''
Variables need type hints (even if they are obvious)

2024-02-26 17:56 UTC, Sean-Nishi commented on m1wengine/button.py
>          self.__already_pressed: bool = False
These look good except for the variable mangling. We are trying to follow Google's style guide as closely as possible. Please remove one of the underscores.
You can read more about the styling of "private" variables in python at: https://google.github.io/styleguide/pyguide.html#3162-naming-conventions
tldr: Use only single prepending _ on private variables to represent they are "private" (no variable in python is actually considered private, this is a style choice to help the reader/coder). Then if other classes want to access these private variables add in the @property and @property.setter methods. There should be a few examples already in our codebase.

2024-02-26 17:57 UTC, Sean-Nishi commented on m1wengine/button.py
> +        self.__text: Text = Text(x, y, self.button_text)
Same comment as above. Only have one prepending underscore

2024-02-26 18:01 UTC, Sean-Nishi requested changes
![linter](https://github.com/m-one-w/M1WEngine/assets/22729669/68ccbdbe-59c3-4995-9138-4b5ead474fe1)
You are so close! Just a few stylistic changes to make sure we are adhering to some sort of standard.
Also, for the failed lint check, once you make the changes I request if you run the command "./linter.sh" into your development environment then black will tell you what is wrong with the styling in this file. Make those additional changes and I will re-review. Then it should be good to go.

2024-03-09 11:20 UTC, owalk requested changes

2024-03-09 11:20 UTC, owalk commented on m1wengine/button.py
> +        self.button_text = ''
```Suggestion
        # Splits text into a list
        self.index: int = 0
        self.Button_Texts_List: list = []
        self.button_text: str = ''
```

2024-03-09 11:20 UTC, owalk commented on m1wengine/button.py
> +        # Clicking functionaliti
```Suggestion
        # Clicking functionality
```

2024-03-09 11:20 UTC, owalk commented on m1wengine/button.py
>          self.__already_pressed: bool = False
plus one, I honestly forgot about this ^ 

As a Python newbie not having the concept of private variables is so strange. Pretty much any doc online I checked agrees with the Google style of not mangling privates -_-

2024-03-09 11:22 UTC, owalk commented on m1wengine/button.py
> -"""This module contains the Button class."""
Removing this docstring is causing the linter to fail here

2024-03-09 11:24 UTC, owalk commented on m1wengine/button.py
> +
this blank line causes the linter to fail

2024-03-09 11:24 UTC, owalk commented on m1wengine/button.py
> +        Increase the index to change the displayed text and
the lack of newline here causes the linter to fail

2024-08-19 18:45 UTC, closed without merging