Add working test environment
m-one-w/M1WEngine pull request #236
Opened 2024-02-21 20:48 UTC by owalk

This involves several hotfixes to quickly get this up and running. Additional work is needed to ensure the library code is generic as intended.

2024-02-23 18:14 UTC, Sean-Nishi commented on m1wengine/managers/asset_manager.py
> +        self._game_data = game_data
Need docstrings for private vars

2024-02-23 18:20 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/minotaur.py
> +        self._radar.center = self.rect.center
Don't we have a property tag when calling _radar?

2024-02-23 18:21 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/minotaur.py
> +        image = self.animate()
type hint

2024-02-23 18:22 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/skeleton.py
> +
Need docstrings for skeleton_movements_path and skeleton_image_rect

2024-02-23 18:23 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/skeleton.py
> +        self._radar.center = self.rect.center
_radar unsafely accessed

2024-02-23 18:23 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/skeleton.py
> +            except ValueError:
Should raise instead of except

2024-02-23 18:25 UTC, Sean-Nishi commented on test/test_src/good_NPCs/damsel.py
> +        self._radar.center = self.rect.center
_radar property method needed

2024-02-23 18:26 UTC, Sean-Nishi commented on test/test_src/heads_up_display.py
> +    Attributes
Docstrings for static consts defined on lines 39-41

2024-02-23 18:27 UTC, Sean-Nishi commented on test/test_src/items/crystal.py
> +    collisions_handler(self)
docstring for init

2024-02-23 18:28 UTC, Sean-Nishi commented on test/test_src/items/crystal.py
> +    def __init__(self, group: pygame.sprite.Group, pos: tuple):
Return val typehint

2024-02-23 18:28 UTC, Sean-Nishi commented on test/test_src/items/crystal.py
> +    def collision_handler(self):
Return val typehint

2024-02-23 18:29 UTC, Sean-Nishi commented on test/test_src/level.py
> +        Draw and update all sprite groups
Need return value type hints in the docstring

2024-02-23 18:31 UTC, Sean-Nishi commented on test/test_src/neutral_NPCs/postman.py
> +    -------
init docstring needed

2024-02-23 18:32 UTC, Sean-Nishi commented on test/test_src/neutral_NPCs/postman.py
> +        self._radar.center = self.rect.center
radar needs to be accessed safely

2024-02-23 18:45 UTC, owalk commented on test/test_src/bad_NPCs/skeleton.py
> +            except ValueError:
this would be the client-side code, so errors should be handled here. A print statement is a solid first step. A more complete solution would be to log errors to the appropriate logging level, and also to a log file, and close the program with an error code

the only improvement here I can think of is a smoother shutdown process

2024-02-23 18:46 UTC, owalk commented on test/test_src/bad_NPCs/skeleton.py
> +        self._radar.center = self.rect.center
yeah, but it is kinda "protected" and this very much so follows the rules of protected variables

2024-02-23 18:48 UTC, owalk commented on test/test_src/bad_NPCs/minotaur.py
> +            except ValueError:
this isn't the game engine code, it's a specific game. the testing environment is functionally a game, or in other words client-side code

2024-02-23 18:49 UTC, owalk commented on test/test_src/bad_NPCs/minotaur.py
> +        self._radar.center = self.rect.center
we totally should. I'll make one.

As a child this is technically okay since _ means protected, but its just better with setters and getters

2024-02-24 19:03 UTC, owalk commented on test/test_src/bad_NPCs/skeleton.py
> +
those are scoped to just init, not to the class. I did miss the doc strings for image

2024-02-24 19:06 UTC, owalk commented on test/test_src/good_NPCs/damsel.py
> +
added for hitbox and image, those are scoped to init

2024-02-26 17:29 UTC, Sean-Nishi commented on m1wengine/managers/level_manager.py
> +    def __init__(self, game_data, settings) -> None:
docstring for params

2024-02-26 17:29 UTC, Sean-Nishi commented on m1wengine/tiles/entities/characters/NPCs/NPC.py
> +    def radar(self, new_value: pygame.rect):
Need "raises" docstring

2024-02-26 17:30 UTC, Sean-Nishi commented on test/test_src/bad_NPCs/minotaur.py
> +        Raises:
Raises should have underscores under it. See other docstrings

2024-02-26 17:33 UTC, Sean-Nishi commented on test/test_src/level.py
> +    _extra_sprites
typehint

2024-02-26 17:34 UTC, Sean-Nishi commented on test/test_src/level.py
> +        """Read level data from gameData.py and stage it for rendering."""
docstrings for parameters

2024-02-26 17:35 UTC, Sean-Nishi requested changes
Just a few more comments. I hope your first day on the job wasn't too stressful :)

2024-03-09 10:22 UTC, owalk commented
> Just a few more comments. I hope your first day on the job wasn't too stressful :)

It's been fantastic!! I think once I get passed the initial knowledge gap phase of learn all the hardware and software stacks, I'll have a lot more free time to work on PRs for this project after work :)

2024-03-09 10:39 UTC, owalk commented
Don't forget to close out conversations as you review since we now need to have 0 unresolved conversations to merge

2024-03-17 21:31 UTC, Sean-Nishi requested changes
Just the one docstring title

2024-03-19 22:34 UTC, owalk commented on test/test_src/bad_NPCs/minotaur.py
> +        Raises:
This has been fixed, please close out any stale comment threads since it will block the PR from getting on main  😨

2024-03-22 14:25 UTC, Sean-Nishi approved these changes
Nicely done!

2024-03-22 14:29 UTC, Sean-Nishi approved these changes
Needed to resolve conversations

2024-03-25 23:37 UTC, merged