219 add game over menu methods
m-one-w/M1WEngine pull request #238
Opened 2024-02-26 18:39 UTC by Sean-Nishi

Added the methods for game_over_success and failure. Currently the pop-up game over menu only has stub methods. Need new issues to fully implement each button

2024-03-08 22:43 UTC, owalk commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +    This class will create two text boxes containing current_score
This will be stale so fast, fine as is but would be better as a more general description of the context of the class

2024-03-09 10:34 UTC, owalk requested changes

2024-03-09 10:34 UTC, owalk commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +        super().__init__(
the only reason to get the massive list of optional arguments here is to pass it into super. either trim the arguments or pass into super

2024-03-09 10:34 UTC, owalk commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +        """Call user selects Restart Level game over menu option."""
why is restart caps here?

2024-03-09 10:34 UTC, owalk commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +        """Call user selects Return to Main Menu game_over_menu option."""
why is return caps here?

2024-03-09 10:34 UTC, owalk commented on m1wengine/managers/level_manager.py
> -        self._clock.tick(FPS)
is this re-added somewhere? maybe in the client-side code?
Seems like it makes sense to have it hanging out in the main method as general setup logic - client side.

2024-03-10 19:24 UTC, Sean-Nishi commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +    This class will create two text boxes containing current_score
Would it make more sense to just move this file to the game repo and not worry about this feature in the engine? If the users of the engine want a game over menu they can make it themselves using pygame_menu like what we did for our game. or a contributor could implement this feature but better?

2024-03-11 00:55 UTC, owalk commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +    This class will create two text boxes containing current_score
Maybe, I'd say since the organization has already been done this way it makes sense to update the comment and push with the current organization and then add a backlog task to refactor whenever scheduling allows for that.

I think it kinda does belong in the client side code unless the logic is a whole lot more generalized than it currently is, but this is fine for now

2024-03-12 15:48 UTC, Sean-Nishi commented on m1wengine/menus/game_over_menu/game_over_menu.py
> +    This class will create two text boxes containing current_score
I've given it some thought and I instead of approving this then creating a new backlog issue to put it into the client I will just move it over to the client now

2024-03-12 16:54 UTC, Sean-Nishi commented
Ok, git is weird right now but I deleted the commit that introduced the game_over_menu to the engine. I kept the rest of the commits as the changes they contain are needed to deal with the game_over_menu which will now be introduced in the client side.

2024-03-20 02:26 UTC, owalk approved these changes

2024-03-22 14:21 UTC, merged